---
{{- if .Values.envSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "query-exporter-helm.fullname" . }}-secretmap
  labels:
    {{- include "query-exporter-helm.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.envSecrets -}}
{{ printf "%s: %s" $k ($v | b64enc | quote) | nindent 2 }}
{{ end -}}
{{- end }}
